import { family, type Family } from "../engines";
import type { Column, Design, Rel, Table } from "../types";

// Names that at least one supported engine treats as a keyword; these are always quoted.
const RESERVED = new Set("all analyze and any as asc between by case check column condition constraint create cross current_date current_time current_timestamp current_user database default delete desc distinct drop else end exists false for foreign from full grant group groups having in index inner insert interval into is join key keys left like limit match natural not null offset on option or order outer primary range rank read references right row rows schema select set table then to trigger true union unique update usage user using values when where window with write".split(" "));

function quoter(f: Family) {
  const [l, r] = f === "mysql" || f === "mariadb" ? ["`", "`"] : f === "mssql" ? ["[", "]"] : ['"', '"'];
  return (name: string) => (/^[a-z_][a-z0-9_]*$/.test(name) && !RESERVED.has(name) ? name : l + name.split(r).join(r + r) + r);
}

const str = (s: string) => "'" + s.replace(/'/g, "''") + "'";

// CREATE TABLE / index / foreign key statements for the design's engine.
export function generateSql(design: Design): string {
  const f = family(design.engine);
  const q = quoter(f);
  const out: string[] = ["-- " + design.name + " · " + design.engine, "-- Generated by Joinery", ""];
  const by: Record<string, Table> = {};
  design.tables.forEach((t) => { by[t.id] = t; });
  const enums = new Map(design.enums.map((e) => [e.name, e.values]));
  // Foreign key columns of one-to-one relationships must be unique.
  const oneToOne = new Set(design.rels.filter((r) => r.one).map((r) => r.from.t + "." + r.from.c));
  const colName = (t: Table, id: string) => { const c = t.cols.find((x) => x.id === id); return c ? q(c.name) : ""; };

  if (f === "postgres") {
    design.enums.forEach((e) => out.push("CREATE TYPE " + q(e.name) + " AS ENUM (" + e.values.map(str).join(", ") + ");"));
    if (design.enums.length) out.push("");
  }

  const fkClause = (r: Rel, S: Table, T: Table) => {
    let s = "FOREIGN KEY (" + colName(S, r.from.c) + ") REFERENCES " + q(T.name) + " (" + colName(T, r.to.c) + ")";
    const act = (a?: string) => (a && a !== "NO ACTION" && !(f === "mssql" && a === "RESTRICT") ? a : "");
    if (act(r.onDelete)) s += " ON DELETE " + r.onDelete;
    if (act(r.onUpdate)) s += " ON UPDATE " + r.onUpdate;
    return s;
  };
  const relsOf = (t: Table) => design.rels.filter((r) => r.from.t === t.id && by[r.to.t] && colName(t, r.from.c) && colName(by[r.to.t], r.to.c));

  const colType = (c: Column): { type: string; check: string } => {
    const values = enums.get(c.type);
    if (!values) return { type: c.type || "text", check: "" };
    if (f === "postgres") return { type: q(c.type), check: "" };
    const list = values.map(str).join(", ");
    if (f === "mysql" || f === "mariadb") return { type: "ENUM(" + list + ")", check: "" };
    return { type: f === "mssql" ? "nvarchar(64)" : "text", check: " CHECK (" + q(c.name) + " IN (" + list + "))" };
  };

  design.tables.forEach((t) => {
    const pks = t.cols.filter((c) => c.pk);
    const inlinePk = pks.length === 1;
    const lines: string[] = [];
    if (t.comment && f !== "postgres" && f !== "mysql" && f !== "mariadb") out.push("-- " + t.comment);
    t.cols.forEach((c) => {
      const { type, check } = colType(c);
      let s = "  " + q(c.name) + " " + type;
      const sqliteRowid = f === "sqlite" && c.autoInc && inlinePk && c.pk;
      if (sqliteRowid) s = "  " + q(c.name) + " INTEGER PRIMARY KEY AUTOINCREMENT";
      else {
        if (c.autoInc) s += f === "postgres" ? " GENERATED BY DEFAULT AS IDENTITY" : f === "mssql" ? " IDENTITY(1,1)" : f === "sqlite" ? "" : " AUTO_INCREMENT";
        if (!c.nullable || c.pk) s += " NOT NULL";
        if (c.def) s += " DEFAULT " + c.def;
        if (inlinePk && c.pk) s += " PRIMARY KEY";
        else if (c.unique || oneToOne.has(t.id + "." + c.id)) s += " UNIQUE";
        s += check;
      }
      if (c.comment && (f === "mysql" || f === "mariadb")) s += " COMMENT " + str(c.comment);
      lines.push(s);
    });
    if (pks.length > 1) lines.push("  PRIMARY KEY (" + pks.map((c) => q(c.name)).join(", ") + ")");
    if (f === "sqlite") relsOf(t).forEach((r) => lines.push("  " + fkClause(r, t, by[r.to.t])));
    let tail = ")";
    if (t.comment && (f === "mysql" || f === "mariadb")) tail += " COMMENT=" + str(t.comment);
    out.push("CREATE TABLE " + q(t.name) + " (", lines.join(",\n"), tail + ";");
    if (f === "postgres") {
      if (t.comment) out.push("COMMENT ON TABLE " + q(t.name) + " IS " + str(t.comment) + ";");
      t.cols.filter((c) => c.comment).forEach((c) => out.push("COMMENT ON COLUMN " + q(t.name) + "." + q(c.name) + " IS " + str(c.comment!) + ";"));
    }
    out.push("");
  });

  const indexes: string[] = [];
  design.tables.forEach((t) => {
    const seen = new Set<string>();
    const add = (name: string, cols: string[], unique: boolean) => {
      const list = cols.map((id) => colName(t, id)).filter(Boolean);
      if (!list.length || seen.has(name)) return;
      seen.add(name);
      indexes.push("CREATE " + (unique ? "UNIQUE " : "") + "INDEX " + q(name) + " ON " + q(t.name) + " (" + list.join(", ") + ");");
    };
    (t.indexes || []).forEach((x) => add(x.name, x.cols, x.unique));
    // MySQL and MariaDB index foreign key columns on their own.
    if (f !== "mysql" && f !== "mariadb") relsOf(t).forEach((r) => {
      const c = t.cols.find((x) => x.id === r.from.c)!;
      const covered = c.unique || r.one || (c.pk && t.cols.filter((x) => x.pk).length === 1) || (t.indexes || []).some((x) => x.cols[0] === c.id);
      if (!covered) add(t.name + "_" + c.name + "_idx", [c.id], false);
    });
  });
  if (indexes.length) out.push(...indexes, "");

  if (f !== "sqlite") {
    const fks: string[] = [];
    design.tables.forEach((t) => relsOf(t).forEach((r) => {
      const c = t.cols.find((x) => x.id === r.from.c)!;
      fks.push("ALTER TABLE " + q(t.name) + " ADD CONSTRAINT " + q(t.name + "_" + c.name + "_fkey") + " " + fkClause(r, t, by[r.to.t]) + ";");
    }));
    if (fks.length) out.push(...fks, "");
  }
  return out.join("\n");
}
